// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFosZc2aNgCZ4-FIvxLiyNcgzDqJGwTKY',
    appId: '1:135766271294:web:a6c17edbeb07a0b592f86f',
    messagingSenderId: '135766271294',
    projectId: 'ukk-cafe-3da28',
    authDomain: 'ukk-cafe-3da28.firebaseapp.com',
    storageBucket: 'ukk-cafe-3da28.appspot.com',
    measurementId: 'G-KGFW614PLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuePupUH6FvKCBUzpXqfkiBq8shf4y340',
    appId: '1:135766271294:android:6cb57ea6b9eb1cb692f86f',
    messagingSenderId: '135766271294',
    projectId: 'ukk-cafe-3da28',
    storageBucket: 'ukk-cafe-3da28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFhdCatIglKLtRcEjUHEt7j_HIDNFL_X0',
    appId: '1:135766271294:ios:24e8720c32597d6892f86f',
    messagingSenderId: '135766271294',
    projectId: 'ukk-cafe-3da28',
    storageBucket: 'ukk-cafe-3da28.appspot.com',
    iosBundleId: 'com.example.ukkCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFhdCatIglKLtRcEjUHEt7j_HIDNFL_X0',
    appId: '1:135766271294:ios:24e8720c32597d6892f86f',
    messagingSenderId: '135766271294',
    projectId: 'ukk-cafe-3da28',
    storageBucket: 'ukk-cafe-3da28.appspot.com',
    iosBundleId: 'com.example.ukkCafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFosZc2aNgCZ4-FIvxLiyNcgzDqJGwTKY',
    appId: '1:135766271294:web:dc8b45caa7d996ea92f86f',
    messagingSenderId: '135766271294',
    projectId: 'ukk-cafe-3da28',
    authDomain: 'ukk-cafe-3da28.firebaseapp.com',
    storageBucket: 'ukk-cafe-3da28.appspot.com',
    measurementId: 'G-4K2SGC2KR5',
  );
}
